# Generated by Django 5.2.12 on 2026-04-19 02:11

import deals.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('legal_name', models.CharField(max_length=200)),
                ('vintage_year', models.IntegerField()),
                ('target_size_npr', models.DecimalField(decimal_places=2, max_digits=15)),
                ('committed_capital_npr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('RAISING', 'Raising'), ('INVESTING', 'Investing'), ('HARVESTING', 'Harvesting'), ('CLOSED', 'Closed')], default='RAISING', max_length=20)),
                ('preferred_return_pct', models.FloatField(default=8.0)),
                ('carry_pct', models.FloatField(default=20.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pe_funds',
                'ordering': ['-vintage_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImmutableAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_STATUS_CHANGED', 'Project Status Changed'), ('INVITATION_SENT', 'Invitation Sent'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('FORM_STEP_SAVED', 'Form Step Saved'), ('PROJECT_SUBMITTED', 'Project Submitted'), ('INVESTMENT_CREATED', 'Investment Created'), ('CAPITAL_CALL_ISSUED', 'Capital Call Issued'), ('DISTRIBUTION_MADE', 'Distribution Made')], max_length=50)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('content_type_label', models.CharField(blank=True, help_text="e.g. 'deals.PEProject'", max_length=100)),
                ('payload', models.JSONField(default=dict, help_text='Arbitrary context: old/new values, metadata, etc.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pe_audit_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LPFundCommitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('committed_amount_npr', models.DecimalField(decimal_places=2, max_digits=15)),
                ('called_amount_npr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('commitment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lp_commitments', to='deals.fund')),
            ],
            options={
                'db_table': 'lp_fund_commitments',
                'ordering': ['-commitment_date'],
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distribution_date', models.DateField()),
                ('amount_npr', models.DecimalField(decimal_places=2, max_digits=15)),
                ('distribution_type', models.CharField(choices=[('RETURN_OF_CAPITAL', 'Return of Capital'), ('PREFERRED_RETURN', 'Preferred Return'), ('CARRIED_INTEREST', 'Carried Interest'), ('DIVIDEND', 'Dividend')], default='RETURN_OF_CAPITAL', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='deals.fund')),
                ('lp_commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='deals.lpfundcommitment')),
            ],
            options={
                'db_table': 'pe_distributions',
                'ordering': ['-distribution_date'],
            },
        ),
        migrations.CreateModel(
            name='CapitalCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount_npr', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CALLED', 'Called'), ('RECEIVED', 'Received'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20)),
                ('notice_sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_calls', to='deals.fund')),
                ('lp_commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_calls', to='deals.lpfundcommitment')),
            ],
            options={
                'db_table': 'pe_capital_calls',
                'ordering': ['-call_date'],
            },
        ),
        migrations.CreateModel(
            name='LPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('accredited_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lp_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lp_profiles',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='lpfundcommitment',
            name='lp_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_commitments', to='deals.lpprofile'),
        ),
        migrations.CreateModel(
            name='PEFormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_type', models.CharField(choices=[('DEAL_SUBMISSION', 'Deal Submission'), ('LP_ONBOARDING', 'LP Onboarding')], default='DEAL_SUBMISSION', max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('steps', models.JSONField(default=list, help_text='Ordered list of step definitions. Each element: {"step_index": 1, "step_name": "company_info", "title": "Company Info", "fields": [...]}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pe_form_templates',
                'ordering': ['-version'],
                'unique_together': {('form_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PEProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=200)),
                ('ocr_registration_number', models.CharField(help_text='Nepal OCR registration number e.g. 12345/67/68', max_length=50, unique=True, validators=[deals.models.validate_ocr_number])),
                ('deal_type', models.CharField(choices=[('GROWTH', 'Growth Capital'), ('BUYOUT', 'Buyout'), ('RECAP', 'Recapitalisation')], default='GROWTH', max_length=20)),
                ('sector', models.CharField(choices=[('Hydropower', 'Hydropower'), ('Banking', 'Banking & Finance'), ('Manufacturing', 'Manufacturing'), ('Tourism', 'Tourism & Hospitality'), ('IT', 'Information Technology'), ('Agriculture', 'Agriculture'), ('Infrastructure', 'Infrastructure'), ('Health', 'Healthcare'), ('Education', 'Education'), ('Retail', 'Retail & FMCG'), ('Other', 'Other')], default='Other', max_length=50)),
                ('investment_range_min_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('investment_range_max_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SCREENING', 'Screening'), ('AI_REVIEW_NEEDED', 'AI Review Needed'), ('GP_APPROVED', 'GP Approved'), ('SHORTLISTED', 'Shortlisted'), ('VIDEO_PITCH', 'Video Pitch'), ('DUE_DILIGENCE', 'Due Diligence'), ('TERM_SHEET', 'Term Sheet'), ('CLOSED', 'Closed'), ('DECLINED', 'Declined')], default='SUBMITTED', max_length=30)),
                ('submission_type', models.CharField(choices=[('MANUAL_GP', 'Manual (GP Created)'), ('ENTREPRENEUR_INVITED', 'Entrepreneur Invited')], default='MANUAL_GP', max_length=30)),
                ('invitation_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('form_step_completed', models.IntegerField(default=0, help_text='Index of last completed form step (0 = none completed)')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pe_projects', to=settings.AUTH_USER_MODEL)),
                ('entrepreneur_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_pe_projects', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pe_projects', to='deals.fund')),
            ],
            options={
                'db_table': 'pe_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PEInvestment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investment_date', models.DateField()),
                ('investment_amount_npr', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ownership_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('valuation_at_entry_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_value_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('exit_type', models.CharField(blank=True, choices=[('TRADE_SALE', 'Trade Sale'), ('IPO', 'IPO'), ('SECONDARY', 'Secondary Sale'), ('WRITE_OFF', 'Write-Off')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='deals.fund')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='deals.peproject')),
            ],
            options={
                'db_table': 'pe_investments',
                'ordering': ['-investment_date'],
            },
        ),
        migrations.CreateModel(
            name='PEProjectDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_key', models.CharField(help_text='Backblaze B2 object key (path within bucket)', max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('FINANCIAL', 'Financial'), ('LEGAL', 'Legal'), ('COMMERCIAL', 'Commercial'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='deals.peproject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_pe_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pe_project_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PEProjectFormResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_index', models.PositiveIntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('response_data', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='deals.peproject')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='deals.peformtemplate')),
            ],
            options={
                'db_table': 'pe_project_form_responses',
                'ordering': ['step_index'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='lpfundcommitment',
            unique_together={('lp_profile', 'fund')},
        ),
        migrations.AddIndex(
            model_name='peproject',
            index=models.Index(fields=['status'], name='idx_pep_status'),
        ),
        migrations.AddIndex(
            model_name='peproject',
            index=models.Index(fields=['fund'], name='idx_pep_fund'),
        ),
        migrations.AddIndex(
            model_name='peproject',
            index=models.Index(fields=['entrepreneur_user'], name='idx_pep_entrepreneur'),
        ),
        migrations.AddIndex(
            model_name='peproject',
            index=models.Index(fields=['invitation_token'], name='idx_pep_token'),
        ),
        migrations.AlterUniqueTogether(
            name='peprojectformresponse',
            unique_together={('project', 'step_index')},
        ),
    ]
