# Generated by Django 5.2.6 on 2026-04-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_default_pe_form_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='peprojectdocument',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='True if client confirmed successful upload to B2'),
        ),
    ]
