# Generated by Django 5.2.12 on 2026-04-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_peprojectdocument_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='peprojectdocument',
            name='is_lp_visible',
            field=models.BooleanField(default=False, help_text='If True, this document will be visible in the LP portal for qualifying investors.'),
        ),
    ]
