# Generated by Django 5.2.12 on 2026-04-19 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_peprojectdocument_is_lp_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peprojectdocument',
            name='is_lp_visible',
        ),
        migrations.CreateModel(
            name='FundDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('LPA', 'Limited Partnership Agreement'), ('PPM', 'Private Placement Memorandum'), ('CAPITAL_CALL', 'Capital Call Notice'), ('DISTRIBUTION', 'Distribution Notice'), ('QUARTERLY_REPORT', 'Quarterly Progress Report'), ('ANNUAL_REPORT', 'Annual Audited Report'), ('TAX_DOCUMENT', 'Tax Certificate/Document'), ('KYC_AML', 'KYC/AML Document'), ('OTHER', 'Other Fund Document')], default='OTHER', max_length=30)),
                ('file_key', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('requires_acknowledgment', models.BooleanField(default=False)),
                ('capital_call_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('capital_call_due_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='deals.fund')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pe_fund_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LPDocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='deals.funddocument')),
                ('lp_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access', to='deals.lpprofile')),
            ],
            options={
                'db_table': 'pe_lp_document_access',
                'unique_together': {('lp_profile', 'document')},
            },
        ),
    ]
