# Generated by Django 5.2.12 on 2026-04-19 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_remove_peprojectdocument_is_lp_visible_funddocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='funddocument',
            name='document_type',
            field=models.CharField(choices=[('LPA', 'Limited Partnership Agreement'), ('PPM', 'Private Placement Memorandum'), ('CAPITAL_CALL', 'Capital Call Notice'), ('DISTRIBUTION', 'Distribution Notice'), ('QUARTERLY_REPORT', 'Quarterly Progress Report'), ('ANNUAL_REPORT', 'Annual Audited Report'), ('TAX_DOCUMENT', 'Tax Certificate/Document'), ('KYC_AML', 'KYC/AML Document'), ('SHAREHOLDER_REPORT', 'GP Shareholder Report'), ('BOARD_MINUTES', 'Board Meeting Minutes'), ('OTHER', 'Other Fund Document')], default='OTHER', max_length=30),
        ),
        migrations.CreateModel(
            name='GPShareholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shares_held', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vesting_status', models.CharField(default='Fully Vested', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gp_shareholding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GP Shareholder',
                'verbose_name_plural': 'GP Shareholders',
                'db_table': 'pe_gp_shareholders',
            },
        ),
        migrations.CreateModel(
            name='GPDividend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_npr', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateField()),
                ('fiscal_year', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PAID', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='deals.gpshareholder')),
            ],
            options={
                'db_table': 'pe_gp_dividends',
                'ordering': ['-payment_date'],
            },
        ),
    ]
