# Generated by Django 5.2.12 on 2026-04-20 03:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_auto_20260420_0851'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QoEReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_text', models.TextField()),
                ('analysis_data', models.JSONField(default=dict, help_text='Structured flags and scores')),
                ('status', models.CharField(choices=[('CLEAN', 'Green'), ('CAUTION', 'Yellow'), ('HIGH_RISK', 'Red')], default='CLEAN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qoe_reports', to='deals.peproject')),
            ],
            options={
                'db_table': 'pe_qoe_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedFinancials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year_bs', models.CharField(help_text='e.g. 2080/81', max_length=10)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ebitda', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pat', models.DecimalField(decimal_places=2, default=0, help_text='Profit After Tax', max_digits=15)),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gross_margin_pct', models.FloatField(default=0)),
                ('ebitda_margin_pct', models.FloatField(default=0)),
                ('pat_margin_pct', models.FloatField(default=0)),
                ('revenue_yoy_growth', models.FloatField(default=0)),
                ('ebitda_yoy_growth', models.FloatField(default=0)),
                ('extraction_confidence', models.FloatField(default=0, help_text='0.0 to 1.0 scale')),
                ('raw_ai_output', models.JSONField(blank=True, default=dict)),
                ('is_verified_by_gp', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='deals.peproject')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.peprojectdocument')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_financials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pe_extracted_financials',
                'ordering': ['-fiscal_year_bs'],
                'unique_together': {('project', 'fiscal_year_bs')},
            },
        ),
    ]
