# Generated by Django 5.2.12 on 2026-04-20 03:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_qoereport_extractedfinancials'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_concentration_pct', models.FloatField(default=0)),
                ('top_customer_names', models.TextField(blank=True, help_text='Comma-separated or bulleted list of top customers')),
                ('market_positioning_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.aicalllog')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_analyses', to='deals.peproject')),
            ],
            options={
                'db_table': 'pe_commercial_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('technology_stack', models.JSONField(blank=True, default=dict)),
                ('key_person_risk_score', models.IntegerField(default=0, help_text='1 to 10 scale')),
                ('supply_chain_risks', models.JSONField(blank=True, default=list)),
                ('operational_red_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.aicalllog')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_analyses', to='deals.peproject')),
            ],
            options={
                'db_table': 'pe_operational_analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
