# Generated by Django 5.2.12 on 2026-04-20 03:24

from django.db import migrations


def seed_prompts(apps, schema_editor):
    PromptLibrary = apps.get_model('deals', 'PromptLibrary')
    
    PromptLibrary.objects.get_or_create(
        name="Commercial Analysis",
        task_type="commercial_analysis",
        defaults={
            "system_prompt": "You are a commercial due diligence expert. Analyze the provided company data for customer concentration and market positioning.",
            "user_prompt_template": "Project: {{project_name}}\nSector: {{sector}}\nDetails: {{business_desc}}\n\nIdentify:\n1. Top 3-5 customers (if identifiable).\n2. Estimated customer concentration %.\n3. Detailed market positioning notes.\n\nReturn ONLY JSON:\n{\n  \"customer_concentration_pct\": float,\n  \"top_customer_names\": \"string\",\n  \"market_positioning_notes\": \"string\"\n}",
            "output_schema": {"customer_concentration_pct": "float", "top_customer_names": "string", "market_positioning_notes": "string"},
            "version": 1,
            "is_active": True
        }
    )

    PromptLibrary.objects.get_or_create(
        name="Operational Analysis",
        task_type="operational_analysis",
        defaults={
            "system_prompt": "You are an operational due diligence expert. Analyze technology stack, supply chain, and key person risks.",
            "user_prompt_template": "Project: {{project_name}}\nContext: {{ops_data}}\n\nIdentify:\n1. Technology stack used (JSON format).\n2. Key person risk score (1-10).\n3. Supply chain risks (List).\n4. Operational red flags (List).\n\nReturn ONLY JSON:\n{\n  \"technology_stack\": {},\n  \"key_person_risk_score\": int,\n  \"supply_chain_risks\": [],\n  \"operational_red_flags\": []\n}",
            "output_schema": {"technology_stack": "object", "key_person_risk_score": "int", "supply_chain_risks": "array", "operational_red_flags": "array"},
            "version": 1,
            "is_active": True
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_commercialanalysis_operationalanalysis'),
    ]

    operations = [
        migrations.RunPython(seed_prompts),
    ]

