# Generated by Django 5.2.12 on 2026-04-20 03:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_add_commercial_ops_prompts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedFlagPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern_regex', models.CharField(help_text='Regex pattern to match', max_length=500)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=20)),
                ('description', models.TextField()),
                ('nepal_context_note', models.TextField(blank=True, help_text='Specific relevance to Nepal (e.g. FITTA, SEBON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pe_red_flag_patterns',
            },
        ),
        migrations.CreateModel(
            name='RedFlagFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_snippet', models.TextField(help_text='The text snippet where the match was found')),
                ('severity', models.CharField(max_length=20)),
                ('ai_analysis', models.TextField(blank=True, help_text="AI's explanation of why this is a risk")),
                ('is_reviewed_by_gp', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_flag_findings', to='deals.peprojectdocument')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_flags', to='deals.peproject')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.redflagpattern')),
            ],
            options={
                'db_table': 'pe_red_flag_findings',
                'ordering': ['-created_at'],
            },
        ),
    ]
