# Generated by Django 5.2.12 on 2026-04-20 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_redflagpattern_redflagfinding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_deal_score', models.FloatField(default=0, help_text='Weighted final score (1-10)')),
                ('gp_assessment_summary', models.TextField(blank=True, help_text='Mandatory GP final assessment (>100 words)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_runs', to='deals.peproject')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_scorings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pe_scoring_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pillar', models.CharField(choices=[('F', 'Foresight'), ('I', 'Insight'), ('N', 'Nexus'), ('L', 'Logic'), ('O', 'Odyssey')], max_length=1)),
                ('criterion_id', models.CharField(help_text='e.g. problem_clarity', max_length=50)),
                ('ai_score', models.IntegerField(default=0, help_text='1-10 scale')),
                ('ai_rationale', models.TextField(blank=True)),
                ('ai_confidence', models.FloatField(default=0)),
                ('evidence_quotes', models.JSONField(blank=True, default=list)),
                ('gp_score', models.IntegerField(blank=True, help_text='1-10 scale', null=True)),
                ('gp_notes', models.TextField(blank=True)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scoring_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_scores', to='deals.scoringrun')),
            ],
            options={
                'db_table': 'pe_criterion_scores',
                'unique_together': {('scoring_run', 'criterion_id')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceGate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate_id', models.CharField(choices=[('FITTA', 'FITTA Approval'), ('AML_KYC', 'AML/KYC Clearance'), ('FINANCIAL_AUDIT', 'Financial Audit Verification'), ('LEGAL_STRUCTURE', 'Legal Structure Validity'), ('SEBON_MAPPING', 'SEBON Mapping & Compliance')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='compliance_gates', to='deals.peprojectdocument')),
                ('scoring_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_gates', to='deals.scoringrun')),
            ],
            options={
                'db_table': 'pe_compliance_gates',
                'unique_together': {('scoring_run', 'gate_id')},
            },
        ),
    ]
