# Generated by Django 5.2.12 on 2026-04-20 04:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_scoringrun_criterionscore_compliancegate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('DCF', 'DCF'), ('LBO', 'LBO')], max_length=10)),
                ('assumptions', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='deals.peproject')),
            ],
            options={
                'db_table': 'pe_valuation_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LBOAssumptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_ebitda', models.DecimalField(decimal_places=2, max_digits=20)),
                ('purchase_multiple', models.FloatField()),
                ('debt_financing', models.JSONField(help_text='List of debt tranches with rates/tenures')),
                ('exit_year', models.IntegerField(default=5)),
                ('exit_multiple', models.FloatField()),
                ('valuation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lbo_detail', to='deals.valuationmodel')),
            ],
            options={
                'db_table': 'pe_valuation_lbo_assumptions',
            },
        ),
        migrations.CreateModel(
            name='DCFAssumptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_years', models.IntegerField(default=5)),
                ('revenue_growth_rate', models.FloatField(help_text='Decimal, e.g. 0.15 for 15%')),
                ('ebitda_margin', models.FloatField()),
                ('tax_rate', models.FloatField(default=0.25)),
                ('wacc', models.FloatField()),
                ('terminal_growth_rate', models.FloatField(default=0.03)),
                ('valuation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dcf_detail', to='deals.valuationmodel')),
            ],
            options={
                'db_table': 'pe_valuation_dcf_assumptions',
            },
        ),
    ]
