# Generated by Django 5.2.12 on 2026-04-20 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0014_valuationmodel_lboassumptions_dcfassumptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitta_approval_required', models.BooleanField(default=False)),
                ('fitta_approval_obtained', models.BooleanField(default=False)),
                ('nrb_approval_required', models.BooleanField(default=False)),
                ('nrb_approval_obtained', models.BooleanField(default=False)),
                ('sebon_reporting_compliant', models.BooleanField(default=True)),
                ('industry_specific_license_required', models.BooleanField(default=False)),
                ('industry_specific_license_obtained', models.BooleanField(default=False)),
                ('license_details', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_checklist', to='deals.peproject')),
            ],
            options={
                'db_table': 'pe_regulatory_checklists',
            },
        ),
        migrations.CreateModel(
            name='SEBONFilingDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.funddocument')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pe_sebon_filing_deadlines',
                'ordering': ['due_date'],
            },
        ),
    ]
