# Generated by Django 5.2.12 on 2026-04-20 04:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0016_dealmemo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioKPIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporting_period', models.DateField(help_text='Month of the report (usually first day of month)')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ebitda', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cash_burn', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('headcount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('gp_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_reports', to='deals.peproject')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pe_portfolio_kpi_reports',
                'ordering': ['-reporting_period'],
                'unique_together': {('project', 'reporting_period')},
            },
        ),
    ]
