# Generated by Django 5.2.12 on 2026-04-21 15:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0017_portfoliokpireport'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPKYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='kyc/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('document_type', models.CharField(help_text='e.g. Passport, Citizenship, PAN', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lp_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='deals.lpprofile')),
            ],
            options={
                'db_table': 'pe_lp_kyc_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
