# Generated by Django 5.2.12 on 2026-04-21 16:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0018_lpkycdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurKYBDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='kyb/entrepreneur/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('document_type', models.CharField(help_text='e.g. Incorporation, PAN, Tax Clearance', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneur_kyb_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pe_entrepreneur_kyb_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('expiry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pe_governance_proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IRDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='ir_docs/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('FINANCIAL', 'Financial Report'), ('LEGAL', 'Legal/Regulatory'), ('MEETING', 'Board/Shareholder Meeting'), ('GENERAL', 'General Announcement')], default='GENERAL', max_length=30)),
                ('is_published', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_ir_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pe_ir_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice', models.CharField(choices=[('FOR', 'For'), ('AGAINST', 'Against'), ('ABSTAIN', 'Abstain')], max_length=20)),
                ('shares_at_voting', models.DecimalField(decimal_places=2, max_digits=15)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='deals.governanceproposal')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='deals.gpshareholder')),
            ],
            options={
                'db_table': 'pe_proposal_votes',
                'unique_together': {('proposal', 'shareholder')},
            },
        ),
    ]
