# Generated by Django 5.2.12 on 2026-04-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0019_entrepreneurkybdocument_governanceproposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpprofile',
            name='wants_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications for new deals and updates.'),
        ),
    ]
