# Generated by Django 5.2.12 on 2026-05-01 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0021_alter_funddocument_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterfallModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('assumptions', models.JSONField(default=dict, help_text='hurdle_rate, carry_pct, catchup_pct, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterfall_models', to='deals.fund')),
            ],
            options={
                'db_table': 'pe_waterfall_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterfallRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exit_proceeds', models.DecimalField(decimal_places=2, max_digits=20)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('years_held', models.FloatField(blank=True, null=True)),
                ('outputs', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterfall_runs', to='deals.peinvestment')),
                ('waterfall_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='deals.waterfallmodel')),
            ],
            options={
                'db_table': 'pe_waterfall_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='distribution',
            name='waterfall_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='deals.waterfallrun'),
        ),
    ]
