# Generated by Django 5.2.12 on 2026-05-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0022_waterfallmodel_waterfallrun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funddocument',
            name='document_type',
            field=models.CharField(choices=[('LPA', 'Limited Partnership Agreement'), ('PPM', 'Private Placement Memorandum'), ('CAPITAL_CALL', 'Capital Call Notice'), ('DISTRIBUTION', 'Distribution Notice'), ('QUARTERLY_REPORT', 'LP Quarterly Progress Report'), ('GP_QUARTERLY_REPORT', 'GP Quarterly Report'), ('ANNUAL_REPORT', 'Annual Audited Report'), ('TAX_DOCUMENT', 'Tax Certificate/Document'), ('KYC_AML', 'KYC/AML Document'), ('SHAREHOLDER_REPORT', 'GP Shareholder Report'), ('BOARD_MINUTES', 'Board Meeting Minutes'), ('CAPITAL_ACCOUNT', 'Capital Account Statement'), ('OTHER', 'Other Fund Document')], default='OTHER', max_length=30),
        ),
    ]
