# Generated by Django 5.2.12 on 2026-05-01 10:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0023_alter_funddocument_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilingTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filing_type', models.CharField(max_length=50, unique=True)),
                ('regulatory_basis', models.CharField(max_length=255)),
                ('default_days_offset', models.IntegerField(help_text='Days after period_end_date that filing is due')),
                ('penalty_description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'pe_filing_type_config',
            },
        ),
        migrations.AddField(
            model_name='regulatorychecklist',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regulatorychecklist',
            name='last_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_checklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sebonfilingdeadline',
            name='filing_type',
            field=models.CharField(choices=[('ANNUAL_REPORT', 'Annual Report'), ('QUARTERLY_REPORT', 'Quarterly Report'), ('AGM_REPORT', 'AGM Report'), ('MATERIAL_EVENT', 'Material Event'), ('AML_STR', 'AML STR'), ('TAX_FILING', 'Tax Filing'), ('FUND_AMENDMENT', 'Fund Amendment'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='sebonfilingdeadline',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filing_deadlines', to='deals.fund'),
        ),
        migrations.AddField(
            model_name='sebonfilingdeadline',
            name='penalty_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sebonfilingdeadline',
            name='regulatory_basis',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sebonfilingdeadline',
            name='reminder_days_before',
            field=models.JSONField(default=list, help_text='List of days before deadline to send alerts (e.g. [30, 14, 7, 1])'),
        ),
        migrations.AlterField(
            model_name='immutableauditevent',
            name='event_type',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_STATUS_CHANGED', 'Project Status Changed'), ('INVITATION_SENT', 'Invitation Sent'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('FORM_STEP_SAVED', 'Form Step Saved'), ('PROJECT_SUBMITTED', 'Project Submitted'), ('INVESTMENT_CREATED', 'Investment Created'), ('CAPITAL_CALL_ISSUED', 'Capital Call Issued'), ('DISTRIBUTION_MADE', 'Distribution Made'), ('SEBON_FILING_SUBMITTED', 'SEBON Filing Submitted')], max_length=50),
        ),
        migrations.CreateModel(
            name='ConflictOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('declaration_date', models.DateField(default=django.utils.timezone.now)),
                ('declaration_period', models.CharField(help_text='e.g. FY 2081/82', max_length=100)),
                ('nature_of_conflict', models.TextField()),
                ('mitigation_measures', models.TextField()),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coi_declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pe_conflicts_of_interest',
                'ordering': ['-declaration_date'],
            },
        ),
        migrations.CreateModel(
            name='ExitScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('exit_type', models.CharField(choices=[('TRADE_SALE', 'Trade Sale / Strategic Acquisition'), ('IPO', 'Initial Public Offering (NEPSE)'), ('SECONDARY', 'Secondary Sale to Financial Sponsor'), ('WRITE_OFF', 'Write-Off / Liquidation'), ('DIVIDEND_RECAP', 'Dividend Recapitalisation')], max_length=20)),
                ('target_year', models.IntegerField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('expected_exit_value_npr', models.DecimalField(decimal_places=2, max_digits=20)),
                ('exit_multiple', models.FloatField()),
                ('expected_irr_pct', models.FloatField(blank=True, null=True)),
                ('probability_pct', models.FloatField(default=50.0)),
                ('is_base_case', models.BooleanField(default=False)),
                ('is_approved_by_ic', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ipo_paid_up_capital_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ipo_years_profitable', models.IntegerField(blank=True, null=True)),
                ('ipo_net_worth_per_share_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ipo_face_value_per_share_npr', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('ipo_credit_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('ipo_is_eligible', models.BooleanField(blank=True, null=True)),
                ('ipo_eligibility_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_scenarios', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_scenarios', to='deals.peinvestment')),
            ],
            options={
                'db_table': 'pe_exit_scenarios',
                'ordering': ['target_year', '-expected_exit_value_npr'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_base_case', True)), fields=('investment',), name='unique_base_case_per_investment')],
            },
        ),
        migrations.CreateModel(
            name='ValuationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valuation_date', models.DateField()),
                ('fair_value_npr', models.DecimalField(decimal_places=2, max_digits=20)),
                ('methodology', models.CharField(choices=[('DCF', 'Discounted Cash Flow'), ('MARKET', 'Market Comparables'), ('COST', 'Cost / Book Value'), ('RECENT_TRANSACTION', 'Recent Transaction'), ('OTHER', 'Other')], default='MARKET', max_length=20)),
                ('discount_rate_pct', models.FloatField(blank=True, null=True)),
                ('exit_multiple_used', models.FloatField(blank=True, null=True)),
                ('assumptions', models.JSONField(blank=True, default=dict)),
                ('previous_valuation_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('is_audited', models.BooleanField(default=False)),
                ('auditor_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='deals.peinvestment')),
                ('valuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pe_valuation_records',
                'ordering': ['-valuation_date'],
                'unique_together': {('investment', 'valuation_date')},
            },
        ),
    ]
