# Generated by Django 5.2.12 on 2026-05-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0025_seed_filing_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immutableauditevent',
            name='event_type',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_STATUS_CHANGED', 'Project Status Changed'), ('INVITATION_SENT', 'Invitation Sent'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('FORM_STEP_SAVED', 'Form Step Saved'), ('PROJECT_SUBMITTED', 'Project Submitted'), ('INVESTMENT_CREATED', 'Investment Created'), ('CAPITAL_CALL_ISSUED', 'Capital Call Issued'), ('DISTRIBUTION_MADE', 'Distribution Made'), ('SEBON_FILING_SUBMITTED', 'SEBON Filing Submitted'), ('USER_MANAGEMENT', 'User Management Action'), ('FUND_MANAGEMENT', 'Fund Management Action'), ('PROMPT_MANAGEMENT', 'Prompt Library Action'), ('COMPLIANCE_REVIEW', 'Compliance Review Action')], max_length=50),
        ),
    ]
