# Generated by Django 5.2.12 on 2026-05-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0026_alter_immutableauditevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peprojectdocument',
            name='category',
            field=models.CharField(choices=[('FINANCIALS', 'Financial Statements'), ('LEGAL', 'Legal Documents'), ('COMMERCIAL', 'Commercial'), ('INCORPORATION', 'Incorporation'), ('TAX_CLEARANCE', 'Tax Clearance'), ('KYC', 'KYC Documents'), ('PITCH_DECK', 'Pitch Deck'), ('BUSINESS_PLAN', 'Business Plan'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
