# Generated by Django 5.2.12 on 2026-05-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0027_alter_peprojectdocument_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='peprojectdocument',
            name='local_file',
            field=models.FileField(blank=True, help_text='Stored locally before being moved to B2', null=True, upload_to='pe_projects/documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='peprojectdocument',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='True if confirmed on B2 or local storage'),
        ),
    ]
