# Generated by Django 5.2.12 on 2026-05-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0028_peprojectdocument_local_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peproject',
            name='status',
            field=models.CharField(choices=[('PENDING_SUBMISSION', 'Pending Submission'), ('SUBMITTED', 'Submitted'), ('SCREENING', 'Screening'), ('AI_REVIEW_NEEDED', 'AI Review Needed'), ('GP_APPROVED', 'GP Approved'), ('SHORTLISTED', 'Shortlisted'), ('VIDEO_PITCH', 'Video Pitch'), ('DUE_DILIGENCE', 'Due Diligence'), ('TERM_SHEET', 'Term Sheet'), ('CLOSED', 'Closed'), ('DECLINED', 'Declined')], default='PENDING_SUBMISSION', max_length=30),
        ),
    ]
