# Generated by Django 5.2.12 on 2026-05-04 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0029_alter_peproject_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='peproject',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='Other GP users who are authorized to work on this deal.', related_name='collaborating_pe_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
