# Generated by Django 5.2.12 on 2026-05-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0031_alter_peprojectdocument_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealmemo',
            name='ic_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extractedfinancials',
            name='verified_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='peproject',
            name='analysis_progress',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='peproject',
            name='status',
            field=models.CharField(choices=[('PENDING_SUBMISSION', 'Pending Submission'), ('SUBMITTED', 'Submitted'), ('SCREENING', 'Screening'), ('AI_REVIEW_NEEDED', 'AI Review Needed'), ('GP_APPROVED', 'GP Approved'), ('SHORTLISTED', 'Shortlisted'), ('VIDEO_PITCH', 'Video Pitch'), ('DUE_DILIGENCE', 'Due Diligence'), ('TERM_SHEET', 'Term Sheet'), ('IC_APPROVED', 'IC Approved'), ('LOI_ISSUED', 'LOI Issued'), ('CONTRACT_SIGNED', 'Contract Signed'), ('CLOSED', 'Closed'), ('DECLINED', 'Declined')], default='PENDING_SUBMISSION', max_length=30),
        ),
        migrations.AlterField(
            model_name='peprojectdocument',
            name='category',
            field=models.CharField(choices=[('FINANCIALS', 'Financial Statements'), ('LEGAL', 'Legal Documents'), ('COMMERCIAL', 'Commercial'), ('INCORPORATION', 'Incorporation'), ('TAX_CLEARANCE', 'Tax Clearance'), ('KYC', 'KYC Documents'), ('PITCH_DECK', 'Pitch Deck'), ('BUSINESS_PLAN', 'Business Plan'), ('CONTRACTS', 'Legal Contracts'), ('LOAN_DOCS', 'Loan & Offer Letters'), ('LOI', 'Letter of Intent'), ('SIGNED_CONTRACT', 'Signed Contract'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
