# Generated by Django 5.2.12 on 2026-05-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0033_upgrade_memo_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedfinancials',
            name='total_assets',
        ),
        migrations.RemoveField(
            model_name='extractedfinancials',
            name='total_debt',
        ),
        migrations.AddField(
            model_name='extractedfinancials',
            name='ebitda_npr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='extractedfinancials',
            name='net_profit_npr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit After Tax', max_digits=15),
        ),
        migrations.AddField(
            model_name='extractedfinancials',
            name='revenue_npr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='extractedfinancials',
            name='total_assets_npr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='extractedfinancials',
            name='total_debt_npr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='extractedfinancials',
            name='pat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
