# Generated by Django 5.2.12 on 2026-05-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0034_remove_extractedfinancials_total_assets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalanalysis',
            name='thesis_markdown',
            field=models.TextField(blank=True, null=True),
        ),
    ]
