# Generated by Django 5.2.12 on 2026-05-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0036_alter_peprojectdocument_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peprojectdocument',
            name='category',
            field=models.CharField(choices=[('FINANCIALS', 'Financial Statements'), ('LEGAL', 'Legal Documents'), ('COMMERCIAL', 'Commercial'), ('INCORPORATION', 'Incorporation'), ('TAX_CLEARANCE', 'Tax Clearance'), ('KYC', 'KYC Documents'), ('PITCH_DECK', 'Pitch Deck'), ('BUSINESS_PLAN', 'Business Plan'), ('CONTRACTS', 'Legal Contracts'), ('LOAN_DOCS', 'Loan & Offer Letters'), ('LOI', 'Letter of Intent'), ('SIGNED_CONTRACT', 'Signed Contract'), ('OPERATIONAL_AUDIT', 'Operational Audit'), ('TECH_STACK', 'Technology Stack Info'), ('ORG_CHART', 'Organization Chart'), ('COMPLIANCE', 'Compliance Evidence'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
