# Generated by Django 5.2.12 on 2026-05-09 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0037_alter_peprojectdocument_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalcall',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The deal this capital call is funding', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_calls', to='deals.peproject'),
        ),
        migrations.AlterField(
            model_name='dealmemo',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final'), ('IC_SIGNED', 'IC Signed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='immutableauditevent',
            name='event_type',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_STATUS_CHANGED', 'Project Status Changed'), ('INVITATION_SENT', 'Invitation Sent'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('FORM_STEP_SAVED', 'Form Step Saved'), ('PROJECT_SUBMITTED', 'Project Submitted'), ('INVESTMENT_CREATED', 'Investment Created'), ('INVESTMENT_CLOSED', 'Investment Closed'), ('CAPITAL_CALL_ISSUED', 'Capital Call Issued'), ('CAPITAL_RECEIVED', 'Capital Received'), ('DISTRIBUTION_MADE', 'Distribution Made'), ('SEBON_FILING_SUBMITTED', 'SEBON Filing Submitted'), ('USER_MANAGEMENT', 'User Management Action'), ('FUND_MANAGEMENT', 'Fund Management Action'), ('PROMPT_MANAGEMENT', 'Prompt Library Action'), ('COMPLIANCE_REVIEW', 'Compliance Review Action'), ('VALUATION_OVERRIDE', 'Valuation Override'), ('TERM_OVERRIDE', 'Term Sheet Override'), ('SPA_OVERRIDE', 'SPA Draft Override'), ('IC_MEMO_SIGNED', 'IC Memo Signed'), ('LOI_ISSUED', 'LOI Issued'), ('LOI_SIGNED_BY_ENTREPRENEUR', 'LOI Signed by Entrepreneur'), ('MEMO_FINALIZED', 'IC Memo Finalized'), ('SCORING_OVERRIDE', 'Scoring Override'), ('COMPLIANCE_CLEARED', 'Compliance Gate Cleared'), ('COMPLIANCE_RESET', 'Compliance Gate Reset'), ('DEAL_APPROVED_FOR_LP', 'Deal Approved for LP')], max_length=50),
        ),
        migrations.AlterField(
            model_name='peproject',
            name='status',
            field=models.CharField(choices=[('PENDING_SUBMISSION', 'Pending Submission'), ('SUBMITTED', 'Submitted'), ('SCREENING', 'Screening'), ('IC_REVIEW', 'IC Review'), ('TERM_SHEET', 'Term Sheet'), ('LOI_ISSUED', 'LOI Issued'), ('CONTRACT_SIGNED', 'Contract Signed'), ('CAPITAL_CALLED', 'Capital Called'), ('CLOSED', 'Closed'), ('DECLINED', 'Declined')], default='PENDING_SUBMISSION', max_length=30),
        ),
        migrations.AlterField(
            model_name='peprojectdocument',
            name='category',
            field=models.CharField(choices=[('FINANCIALS', 'Financial Statements'), ('LEGAL', 'Legal Documents'), ('COMMERCIAL', 'Commercial'), ('INCORPORATION', 'Incorporation'), ('TAX_CLEARANCE', 'Tax Clearance'), ('KYC', 'KYC Documents'), ('PITCH_DECK', 'Pitch Deck'), ('BUSINESS_PLAN', 'Business Plan'), ('CONTRACTS', 'Legal Contracts'), ('LOAN_DOCS', 'Loan & Offer Letters'), ('LOI', 'Letter of Intent'), ('LOI_SIGNED', 'Signed LOI'), ('IC_SIGNED', 'Signed IC Memo'), ('SIGNED_CONTRACT', 'Signed Contract'), ('OPERATIONAL_AUDIT', 'Operational Audit'), ('TECH_STACK', 'Technology Stack Info'), ('ORG_CHART', 'Organization Chart'), ('COMPLIANCE', 'Compliance Evidence'), ('SPA_DRAFT', 'SPA Draft'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.CreateModel(
            name='SPADraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sections', models.JSONField(default=dict, help_text='recitals, definitions, purchase_price, representations, conditions_precedent, covenants, indemnification, governing_law')),
                ('ai_generated_sections', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Under Legal Review'), ('FINAL', 'Final')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_drafts', to='deals.peproject')),
            ],
            options={
                'db_table': 'pe_spa_drafts',
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terms', models.JSONField(default=dict, help_text='investment_amount_npr, pre_money_valuation_npr, ownership_pct, board_seats, observer_rights, exclusivity_days, vesting_schedule, exit_strategy_summary')),
                ('ai_generated_terms', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('NEGOTIATING', 'Under Negotiation'), ('AGREED', 'Terms Agreed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_sheets', to='deals.peproject')),
            ],
            options={
                'db_table': 'pe_term_sheets',
                'ordering': ['-version', '-created_at'],
            },
        ),
    ]
