# Generated by Django 5.2.12 on 2026-05-09 12:27
# Data migration: map legacy statuses to the new unified deal flow statuses.

from django.db import migrations


STATUS_MAP = {
    'AI_REVIEW_NEEDED': 'SCREENING',
    'GP_APPROVED': 'IC_REVIEW',
    'SHORTLISTED': 'IC_REVIEW',
    'VIDEO_PITCH': 'IC_REVIEW',
    'DUE_DILIGENCE': 'IC_REVIEW',
    'IC_APPROVED': 'TERM_SHEET',
}


def migrate_statuses_forward(apps, schema_editor):
    """Map legacy statuses to their new equivalents."""
    PEProject = apps.get_model('deals', 'PEProject')
    for old_status, new_status in STATUS_MAP.items():
        count = PEProject.objects.filter(status=old_status).update(status=new_status)
        if count:
            print(f"  Migrated {count} deals: {old_status} -> {new_status}")


def migrate_statuses_reverse(apps, schema_editor):
    """Best-effort reverse mapping."""
    PEProject = apps.get_model('deals', 'PEProject')
    # IC_REVIEW → DUE_DILIGENCE (closest match)
    PEProject.objects.filter(status='IC_REVIEW').update(status='DUE_DILIGENCE')


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0038_unified_deal_flow'),
    ]

    operations = [
        migrations.RunPython(
            migrate_statuses_forward,
            migrate_statuses_reverse,
        ),
    ]
