# Generated by Django 5.2.12 on 2026-05-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0039_migrate_legacy_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immutableauditevent',
            name='event_type',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_STATUS_CHANGED', 'Project Status Changed'), ('INVITATION_SENT', 'Invitation Sent'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('FORM_STEP_SAVED', 'Form Step Saved'), ('PROJECT_SUBMITTED', 'Project Submitted'), ('INVESTMENT_CREATED', 'Investment Created'), ('INVESTMENT_CLOSED', 'Investment Closed'), ('CAPITAL_CALL_ISSUED', 'Capital Call Issued'), ('CAPITAL_CALLED', 'Capital Called'), ('CAPITAL_RECEIVED', 'Capital Received'), ('DISTRIBUTION_MADE', 'Distribution Made'), ('SEBON_FILING_SUBMITTED', 'SEBON Filing Submitted'), ('USER_MANAGEMENT', 'User Management Action'), ('FUND_MANAGEMENT', 'Fund Management Action'), ('PROMPT_MANAGEMENT', 'Prompt Library Action'), ('COMPLIANCE_REVIEW', 'Compliance Review Action'), ('VALUATION_OVERRIDE', 'Valuation Override'), ('TERM_OVERRIDE', 'Term Sheet Override'), ('SPA_OVERRIDE', 'SPA Draft Override'), ('IC_MEMO_SIGNED', 'IC Memo Signed'), ('LOI_ISSUED', 'LOI Issued'), ('LOI_SIGNED_BY_ENTREPRENEUR', 'LOI Signed by Entrepreneur'), ('MEMO_FINALIZED', 'IC Memo Finalized'), ('SCORING_OVERRIDE', 'Scoring Override'), ('COMPLIANCE_CLEARED', 'Compliance Gate Cleared'), ('COMPLIANCE_RESET', 'Compliance Gate Reset'), ('DEAL_APPROVED_FOR_LP', 'Deal Approved for LP')], max_length=50),
        ),
    ]
