# Generated by Django 5.2.12 on 2026-05-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0040_alter_immutableauditevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalcall',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='LP upload for bank transfer proof', null=True, upload_to='payments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='capitalcall',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CALLED', 'Called'), ('PAID', 'Paid (Awaiting Verification)'), ('RECEIVED', 'Received'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20),
        ),
    ]
