# Generated by Django 5.2.12 on 2026-05-15 15:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0042_alter_capitalcall_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPInvestorMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('speaker', models.CharField(help_text='Host/Managing Partner', max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('recording_url', models.URLField(blank=True, max_length=500, null=True)),
                ('meeting_type', models.CharField(choices=[('VIDEO_PROTOCOL', 'Secure Video Protocol'), ('BOARD_SESSION', 'Board/IC Session'), ('TOWN_HALL', 'Shareholder Town Hall'), ('STRATEGIC_REVIEW', 'Strategic Review')], default='VIDEO_PROTOCOL', max_length=30)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pe_gp_investor_meetings',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
