# Generated by Django 5.2.12 on 2026-05-15 16:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0044_gpinvestormeetingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPSupportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lp_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='deals.lpprofile')),
            ],
            options={
                'db_table': 'pe_lp_support_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
