# Generated by Django 5.2.12 on 2026-05-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0045_lpsupportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalcall',
            name='call_type',
            field=models.CharField(choices=[('INVESTMENT', 'Capital Investment'), ('MANAGEMENT_FEE', 'Management Fee'), ('FUND_EXPENSE', 'Fund Expense'), ('OTHER', 'Other')], default='INVESTMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='fund',
            name='management_fee_pct',
            field=models.FloatField(default=2.0),
        ),
    ]
