# Generated by Django 5.2.12 on 2026-05-16 11:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0046_capitalcall_call_type_fund_management_fee_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='investment_period_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='management_fee_basis',
            field=models.CharField(choices=[('COMMITTED', 'Committed Capital'), ('INVESTED', 'Invested Capital')], default='COMMITTED', max_length=20),
        ),
        migrations.AddField(
            model_name='fund',
            name='management_fee_frequency_months',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='fund',
            name='post_investment_management_fee_basis',
            field=models.CharField(blank=True, choices=[('COMMITTED', 'Committed Capital'), ('INVESTED', 'Invested Capital')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='post_investment_management_fee_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lpfundcommitment',
            name='fee_end_date_override',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lpfundcommitment',
            name='fee_start_date_override',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lpfundcommitment',
            name='management_fee_override_basis',
            field=models.CharField(blank=True, choices=[('COMMITTED', 'Committed Capital'), ('INVESTED', 'Invested Capital')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lpfundcommitment',
            name='management_fee_override_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='ManagementFeeAccrual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('accrual_date', models.DateField(help_text='The date this accrual was recorded')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_called', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capital_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_accruals', to='deals.capitalcall')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_accruals', to='deals.fund')),
                ('lp_commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_accruals', to='deals.lpfundcommitment')),
            ],
            options={
                'db_table': 'pe_management_fee_accruals',
                'ordering': ['-accrual_date'],
            },
        ),
    ]
