# Generated by Django 5.2.12 on 2026-05-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0047_fund_investment_period_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementfeeaccrual',
            name='fee_basis_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The capital basis used for calculation', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managementfeeaccrual',
            name='fee_pct_used',
            field=models.FloatField(default=0, help_text='The annual percentage rate used'),
            preserve_default=False,
        ),
    ]
