# Generated by Django 5.2.12 on 2026-05-16 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0048_managementfeeaccrual_fee_basis_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='deals.peproject'),
        ),
        migrations.AddField(
            model_name='lpfundcommitment',
            name='credit_balance_npr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Excess capital credits from equalization or refunds, available for netting.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='capitalcall',
            name='call_type',
            field=models.CharField(choices=[('INVESTMENT', 'Capital Investment'), ('MANAGEMENT_FEE', 'Management Fee'), ('FUND_EXPENSE', 'Fund Expense'), ('EQUALIZATION', 'Equalization Catch-up'), ('OTHER', 'Other')], default='INVESTMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distribution_type',
            field=models.CharField(choices=[('RETURN_OF_CAPITAL', 'Return of Capital'), ('PREFERRED_RETURN', 'Preferred Return'), ('CARRIED_INTEREST', 'Carried Interest'), ('EQUALIZATION_REFUND', 'Equalization Refund'), ('DIVIDEND', 'Dividend')], default='RETURN_OF_CAPITAL', max_length=30),
        ),
    ]
