# Generated by Django 5.2.12 on 2026-05-18 15:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0049_equalization_netting_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='immutableauditevent',
            name='event_type',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_STATUS_CHANGED', 'Project Status Changed'), ('INVITATION_SENT', 'Invitation Sent'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('FORM_STEP_SAVED', 'Form Step Saved'), ('PROJECT_SUBMITTED', 'Project Submitted'), ('INVESTMENT_CREATED', 'Investment Created'), ('INVESTMENT_CLOSED', 'Investment Closed'), ('CAPITAL_CALL_ISSUED', 'Capital Call Issued'), ('CAPITAL_CALLED', 'Capital Called'), ('CAPITAL_RECEIVED', 'Capital Received'), ('DISTRIBUTION_MADE', 'Distribution Made'), ('SEBON_FILING_SUBMITTED', 'SEBON Filing Submitted'), ('USER_MANAGEMENT', 'User Management Action'), ('FUND_MANAGEMENT', 'Fund Management Action'), ('PROMPT_MANAGEMENT', 'Prompt Library Action'), ('COMPLIANCE_REVIEW', 'Compliance Review Action'), ('VALUATION_OVERRIDE', 'Valuation Override'), ('TERM_OVERRIDE', 'Term Sheet Override'), ('SPA_OVERRIDE', 'SPA Draft Override'), ('IC_MEMO_SIGNED', 'IC Memo Signed'), ('LOI_ISSUED', 'LOI Issued'), ('LOI_SIGNED_BY_ENTREPRENEUR', 'LOI Signed by Entrepreneur'), ('MEMO_FINALIZED', 'IC Memo Finalized'), ('SCORING_OVERRIDE', 'Scoring Override'), ('COMPLIANCE_CLEARED', 'Compliance Gate Cleared'), ('COMPLIANCE_RESET', 'Compliance Gate Reset'), ('DEAL_APPROVED_FOR_LP', 'Deal Approved for LP'), ('VALIDATION_SUBMITTED', 'Idea Validation Submitted'), ('QUOTA_ADJUSTED', 'Validator Quota Adjusted'), ('RED_TEAM_REPORT_ACCESSED', 'Red-Team Report Accessed'), ('RED_TEAM_REPORT_TRIGGERED', 'Red-Team Report Triggered'), ('SECTOR_REPORT_EDITED', 'Sector Report Edited'), ('SECTOR_REPORT_PUBLISHED', 'Sector Report Published')], max_length=50),
        ),
        migrations.CreateModel(
            name='SectorReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sector', models.CharField(choices=[('Hydropower', 'Hydropower'), ('Banking', 'Banking & Finance'), ('Manufacturing', 'Manufacturing'), ('Tourism', 'Tourism & Hospitality'), ('IT', 'Information Technology'), ('Agriculture', 'Agriculture'), ('Infrastructure', 'Infrastructure'), ('Health', 'Healthcare'), ('Education', 'Education'), ('Retail', 'Retail & FMCG'), ('Real Estate', 'Real Estate'), ('Fintech', 'Fintech'), ('Other', 'Other')], help_text='One of the 13 Finlogic sectors.', max_length=50)),
                ('report_date', models.DateField(help_text='First day of the quarter, e.g. 2026-01-01 for Q1 2026.')),
                ('title', models.CharField(blank=True, help_text="Auto-generated as '[Sector] Q[quarter] [year] Report'.", max_length=255)),
                ('content', models.TextField(blank=True, help_text='Full AI-generated markdown/HTML report body.')),
                ('summary', models.TextField(blank=True, help_text='Executive summary (3-line digest).')),
                ('source_file', models.FileField(blank=True, help_text='Uploaded data file (CSV, PDF, or image).', null=True, upload_to='sector_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'pdf', 'png', 'jpg', 'jpeg'])])),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Structured data extracted from the uploaded file.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pe_sector_reports',
                'ordering': ['-report_date', '-created_at'],
                'indexes': [models.Index(fields=['sector'], name='idx_sector_report_sector'), models.Index(fields=['status'], name='idx_sector_report_status'), models.Index(fields=['report_date'], name='idx_sector_report_date')],
                'unique_together': {('sector', 'report_date')},
            },
        ),
    ]
