# Generated by Django 5.2.12 on 2026-05-18 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0050_sector_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparableCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Company name (e.g. 'Nabil Bank Limited').", max_length=255)),
                ('ticker', models.CharField(blank=True, help_text="NEPSE ticker symbol (e.g. 'NABIL').", max_length=20)),
                ('sector', models.CharField(blank=True, choices=[('Hydropower', 'Hydropower'), ('Banking', 'Banking & Finance'), ('Manufacturing', 'Manufacturing'), ('Tourism', 'Tourism & Hospitality'), ('IT', 'Information Technology'), ('Agriculture', 'Agriculture'), ('Infrastructure', 'Infrastructure'), ('Health', 'Healthcare'), ('Education', 'Education'), ('Retail', 'Retail & FMCG'), ('Real Estate', 'Real Estate'), ('Fintech', 'Fintech'), ('Other', 'Other')], help_text='NEPSE sector classification.', max_length=50)),
                ('exchange', models.CharField(default='NEPSE', help_text='Stock exchange (default: NEPSE).', max_length=20)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Market capitalisation in NPR.', max_digits=20, null=True)),
                ('ev_ebitda', models.DecimalField(blank=True, decimal_places=2, help_text='Enterprise Value / EBITDA multiple.', max_digits=10, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Price / Earnings ratio.', max_digits=10, null=True)),
                ('pb_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Price / Book Value ratio.', max_digits=10, null=True)),
                ('ev_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Enterprise Value / Revenue multiple.', max_digits=10, null=True)),
                ('last_updated', models.DateField(auto_now=True, help_text='Date of last data update.')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this data has been verified by a GP.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pe_comparable_companies',
                'ordering': ['sector', 'name'],
                'indexes': [models.Index(fields=['ticker'], name='idx_comp_ticker'), models.Index(fields=['sector'], name='idx_comp_sector')],
            },
        ),
    ]
