# Generated by Django 5.2.12 on 2026-05-18 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0051_comparable_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='immutableauditevent',
            name='event_type',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_STATUS_CHANGED', 'Project Status Changed'), ('INVITATION_SENT', 'Invitation Sent'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('FORM_STEP_SAVED', 'Form Step Saved'), ('PROJECT_SUBMITTED', 'Project Submitted'), ('INVESTMENT_CREATED', 'Investment Created'), ('INVESTMENT_CLOSED', 'Investment Closed'), ('CAPITAL_CALL_ISSUED', 'Capital Call Issued'), ('CAPITAL_CALLED', 'Capital Called'), ('CAPITAL_RECEIVED', 'Capital Received'), ('DISTRIBUTION_MADE', 'Distribution Made'), ('SEBON_FILING_SUBMITTED', 'SEBON Filing Submitted'), ('USER_MANAGEMENT', 'User Management Action'), ('FUND_MANAGEMENT', 'Fund Management Action'), ('PROMPT_MANAGEMENT', 'Prompt Library Action'), ('COMPLIANCE_REVIEW', 'Compliance Review Action'), ('VALUATION_OVERRIDE', 'Valuation Override'), ('TERM_OVERRIDE', 'Term Sheet Override'), ('SPA_OVERRIDE', 'SPA Draft Override'), ('IC_MEMO_SIGNED', 'IC Memo Signed'), ('LOI_ISSUED', 'LOI Issued'), ('LOI_SIGNED_BY_ENTREPRENEUR', 'LOI Signed by Entrepreneur'), ('MEMO_FINALIZED', 'IC Memo Finalized'), ('SCORING_OVERRIDE', 'Scoring Override'), ('COMPLIANCE_CLEARED', 'Compliance Gate Cleared'), ('COMPLIANCE_RESET', 'Compliance Gate Reset'), ('DEAL_APPROVED_FOR_LP', 'Deal Approved for LP'), ('VALIDATION_SUBMITTED', 'Idea Validation Submitted'), ('QUOTA_ADJUSTED', 'Validator Quota Adjusted'), ('RED_TEAM_REPORT_ACCESSED', 'Red-Team Report Accessed'), ('RED_TEAM_REPORT_TRIGGERED', 'Red-Team Report Triggered'), ('SECTOR_REPORT_EDITED', 'Sector Report Edited'), ('SECTOR_REPORT_PUBLISHED', 'Sector Report Published'), ('COMPS_UPSERTED', 'Comps Upserted')], max_length=50),
        ),
        migrations.CreateModel(
            name='RegulatoryUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('source_name', models.CharField(choices=[('SEBON', 'SEBON'), ('NRB', 'NRB'), ('IRD', 'IRD'), ('OTHER', 'Other')], max_length=50)),
                ('source_url', models.URLField(blank=True, help_text='Link to original announcement if available', null=True)),
                ('published_date', models.DateField()),
                ('original_file', models.FileField(blank=True, help_text='Uploaded PDF, DOCX, or Image', null=True, upload_to='regulatory_updates/')),
                ('raw_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True, help_text='AI-generated 3-bullet summary')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulatory_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pe_regulatory_updates',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
