[tool:pytest]
DJANGO_SETTINGS_MODULE = finlogic_api.settings
testpaths = 
    tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    --verbose
    --tb=short
    --maxfail=3
    --disable-warnings