# Generated by Django 5.2.12 on 2026-05-13 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaValidationSession',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('current_step', models.IntegerField(default=1, help_text='Progress step (1-5)')),
                ('polished_report', models.TextField(blank=True, help_text='Rich text report visible to user and super-admins.', null=True)),
                ('red_team_report', models.TextField(blank=True, help_text='Rich text report visible ONLY to super-admins.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idea Validation Session',
                'verbose_name_plural': 'Idea Validation Sessions',
                'db_table': 'idea_validation_sessions',
            },
        ),
        migrations.CreateModel(
            name='IdeaValidatorQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_validations', models.IntegerField(default=1)),
                ('last_reset_quarter', models.CharField(help_text='Format: YYYY-QN (e.g., 2026-Q2)', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idea_validator_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idea Validator Quota',
                'verbose_name_plural': 'Idea Validator Quotas',
                'db_table': 'idea_validator_quotas',
            },
        ),
        migrations.CreateModel(
            name='QuotaAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.IntegerField()),
                ('new_value', models.IntegerField()),
                ('change_amount', models.IntegerField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_quota_adjustments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'idea_validator_quota_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationSubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_log', to='idea_validator.ideavalidationsession')),
            ],
            options={
                'db_table': 'idea_validator_submission_logs',
            },
        ),
        migrations.CreateModel(
            name='ValidationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(help_text='1 to 25')),
                ('selected_option', models.TextField(blank=True, null=True)),
                ('other_text', models.TextField(blank=True, null=True)),
                ('free_text_response', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='idea_validator.ideavalidationsession')),
            ],
            options={
                'db_table': 'idea_validation_answers',
                'ordering': ['question_number'],
                'unique_together': {('session', 'question_number')},
            },
        ),
    ]
