# Generated by Django 5.2.12 on 2026-05-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_validator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideavalidationsession',
            name='form_step_completed',
            field=models.IntegerField(default=0, help_text='Highest step completed'),
        ),
        migrations.AddField(
            model_name='ideavalidationsession',
            name='progress_text',
            field=models.CharField(blank=True, help_text="Progress description (e.g., 'Phase 3 of 8')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ideavalidationsession',
            name='verdict',
            field=models.CharField(blank=True, help_text='AI generated verdict (Pass/Fail/etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ideavalidationsession',
            name='current_step',
            field=models.IntegerField(default=1, help_text='Current step being worked on (1-5)'),
        ),
    ]
