# Generated by Django 5.2.12 on 2026-05-13 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_validator', '0002_ideavalidationsession_form_step_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatorPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(help_text="e.g., 'polished_report' or 'red_team_report'", max_length=50, unique=True)),
                ('system_prompt', models.TextField()),
                ('user_prompt_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Validator Prompt',
                'verbose_name_plural': 'Validator Prompts',
                'db_table': 'validator_prompts',
            },
        ),
    ]
