# Generated by Django 5.2.12 on 2026-05-13 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_validator', '0003_validatorprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='Question number (1-25)', unique=True)),
                ('pillar', models.CharField(choices=[('F', 'Foresight'), ('I', 'Insight'), ('N', 'Nexus'), ('L', 'Logic'), ('O', 'Odyssey')], max_length=1)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ne', models.CharField(max_length=255)),
                ('question_en', models.TextField()),
                ('question_ne', models.TextField()),
                ('hint_en', models.TextField(blank=True, null=True)),
                ('hint_ne', models.TextField(blank=True, null=True)),
                ('allow_other', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'idea_validator_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField()),
                ('text_ne', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_list', to='idea_validator.question')),
            ],
            options={
                'db_table': 'idea_validator_options',
                'ordering': ['order'],
            },
        ),
    ]
