# Generated by Django 5.2.12 on 2026-05-15 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('deck', models.TextField(blank=True, help_text="One-line summary or 'deck' for the issue")),
                ('subject_line', models.CharField(blank=True, max_length=255)),
                ('section_signal', models.TextField(blank=True)),
                ('section_thesis', models.TextField(blank=True)),
                ('section_founders', models.TextField(blank=True)),
                ('section_lp', models.TextField(blank=True)),
                ('section_data', models.TextField(blank=True)),
                ('section_question', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True, help_text='Override field for custom HTML if needed')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('target_segment', models.CharField(choices=[('founder', 'Founder'), ('lp', 'LP'), ('international', 'International'), ('general', 'General')], default='general', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('segment', models.CharField(choices=[('founder', 'Founder'), ('lp', 'LP'), ('international', 'International'), ('general', 'General')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsub', 'Unsubscribed'), ('bounced', 'Bounced')], default='active', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnsubscribeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unsub_token', to='newsletter.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='SendEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('bounced', models.BooleanField(default=False)),
                ('bounce_type', models.CharField(blank=True, max_length=50)),
                ('tracking_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_events', to='newsletter.issue')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_events', to='newsletter.subscriber')),
            ],
            options={
                'unique_together': {('issue', 'subscriber')},
            },
        ),
    ]
