# Generated by Django 5.2.12 on 2026-03-11 11:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('entrepreneur', 'Entrepreneur'), ('investor', 'Investor'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='entrepreneur', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'core_user',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('content', models.TextField(blank=True, default='')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='articles/thumbnails/')),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'core_article',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('instructor', models.CharField(blank=True, default='', max_length=255)),
                ('duration', models.DurationField(blank=True, help_text='Estimated course duration.', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/')),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'core_course',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('target_size', models.DecimalField(blank=True, decimal_places=2, help_text='Target fund size in base currency.', max_digits=15, null=True)),
                ('current_size', models.DecimalField(decimal_places=2, default=0, help_text='Current committed capital.', max_digits=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('fully_deployed', 'Fully Deployed')], default='open', max_length=20)),
                ('inception_date', models.DateField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_funds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fund',
                'verbose_name_plural': 'Funds',
                'db_table': 'core_fund',
                'ordering': ['-inception_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestorCommitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pledged', 'Pledged'), ('committed', 'Committed'), ('called', 'Called'), ('distributed', 'Distributed')], default='pledged', max_length=20)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='core.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor Commitment',
                'verbose_name_plural': 'Investor Commitments',
                'db_table': 'core_investor_commitment',
                'ordering': ['-committed_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('investment_date', models.DateField(blank=True, null=True)),
                ('equity_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of equity held (0–100).', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('exited', 'Exited'), ('written_off', 'Written Off')], default='active', max_length=20)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_companies', to='core.fund')),
            ],
            options={
                'verbose_name': 'Portfolio Company',
                'verbose_name_plural': 'Portfolio Companies',
                'db_table': 'core_portfolio_company',
                'ordering': ['-investment_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('submission_data', models.JSONField(blank=True, default=dict, help_text='Structured submission form data.')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, help_text='Aggregate evaluation score.', max_digits=6, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'core_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Flexible key-value store for additional profile data.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'core_user_profile',
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_published', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webinar',
                'verbose_name_plural': 'Webinars',
                'db_table': 'core_webinar',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
