# Generated by Django 5.2.6 on 2026-03-12 12:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.UUIDField()),
                ('action', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SOFT_DELETE', 'Soft Delete')], max_length=20)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('customer', 'Customer'), ('partner', 'Partner')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('meeting', 'Meeting'), ('note', 'Note')], max_length=20)),
                ('description', models.TextField()),
                ('interaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact_interactions',
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('content', models.TextField(blank=True, null=True)),
                ('video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'course_modules',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_name', models.CharField(max_length=100)),
                ('investment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount_invested', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ownership_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deals',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='enrolled', max_length=20)),
                ('progress_percent', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('investor_type', models.CharField(choices=[('individual', 'Individual'), ('family_office', 'Family Office'), ('institutional', 'Institutional')], max_length=20)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('accredited_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'investors',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='LessonCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lesson_completions',
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_comments',
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('category', models.CharField(choices=[('pitch_deck', 'Pitch Deck'), ('financial_model', 'Financial Model'), ('other', 'Other')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_files',
            },
        ),
        migrations.CreateModel(
            name='ProjectScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pillar', models.CharField(choices=[('vision', 'Vision'), ('growth', 'Growth'), ('leadership', 'Leadership'), ('insight', 'Insight'), ('partnership', 'Partnership')], max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_scores',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='WebinarRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('attended', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webinar_registrations',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={},
        ),
        migrations.AlterModelOptions(
            name='investorcommitment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='portfoliocompany',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='webinar',
            options={},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='article',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='current_size',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='inception_date',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='investorcommitment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='investorcommitment',
            name='committed_at',
        ),
        migrations.RemoveField(
            model_name='investorcommitment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='investorcommitment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='portfoliocompany',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfoliocompany',
            name='equity_percentage',
        ),
        migrations.RemoveField(
            model_name='portfoliocompany',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='portfoliocompany',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='portfoliocompany',
            name='status',
        ),
        migrations.RemoveField(
            model_name='portfoliocompany',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='host',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='meeting_url',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='slug',
        ),
        migrations.AddField(
            model_name='article',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pillar',
            field=models.CharField(blank=True, choices=[('vision', 'Vision'), ('growth', 'Growth'), ('leadership', 'Leadership'), ('insight', 'Insight'), ('partnership', 'Partnership')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='course',
            name='featured_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='pillar',
            field=models.CharField(blank=True, choices=[('vision', 'Vision'), ('growth', 'Growth'), ('leadership', 'Leadership'), ('insight', 'Insight'), ('partnership', 'Partnership')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='committed_capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='fund',
            name='vintage_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorcommitment',
            name='called_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='investorcommitment',
            name='commitment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='investorcommitment',
            name='commitment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investorcommitment',
            name='distributed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='portfoliocompany',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfoliocompany',
            name='current_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='portfoliocompany',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliocompany',
            name='exit_type',
            field=models.CharField(blank=True, choices=[('ipo', 'IPO'), ('acquisition', 'Acquisition'), ('secondary', 'Secondary'), ('write_off', 'Write Off')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='portfoliocompany',
            name='exit_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='portfoliocompany',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project'),
        ),
        migrations.AddField(
            model_name='portfoliocompany',
            name='valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='final_decision_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('entrepreneur', 'Entrepreneur'), ('investor', 'Investor'), ('admin', 'Admin')], default='entrepreneur', max_length=20),
        ),
        migrations.AddField(
            model_name='webinar',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='webinar',
            name='pillar',
            field=models.CharField(blank=True, choices=[('vision', 'Vision'), ('growth', 'Growth'), ('leadership', 'Leadership'), ('insight', 'Insight'), ('partnership', 'Partnership')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='recording_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='registration_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='speaker',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='status',
            field=models.CharField(choices=[('raising', 'Raising'), ('closed', 'Closed'), ('fully_invested', 'Fully Invested'), ('liquidating', 'Liquidating')], default='raising', max_length=20),
        ),
        migrations.AlterField(
            model_name='fund',
            name='target_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='portfoliocompany',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='portfoliocompany',
            name='investment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='portfoliocompany',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('declined', 'Declined'), ('approved', 'Approved'), ('invested', 'Invested')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='submission_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='scheduled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user'], name='idx_projects_user'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='idx_projects_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['total_score'], name='idx_projects_score'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='idx_projects_slug'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_users_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_users_role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deleted_at'], name='idx_users_deleted_at'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user', 'profile_type'], name='idx_up_user_type'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='fund',
            table='funds',
        ),
        migrations.AlterModelTable(
            name='investorcommitment',
            table='investor_commitments',
        ),
        migrations.AlterModelTable(
            name='portfoliocompany',
            table='portfolio_companies',
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
        migrations.AlterModelTable(
            name='webinar',
            table='webinars',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactinteraction',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.contact'),
        ),
        migrations.AddField(
            model_name='contactinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.course'),
        ),
        migrations.AddField(
            model_name='deal',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='core.fund'),
        ),
        migrations.AddField(
            model_name='deal',
            name='portfolio_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='core.portfoliocompany'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investorcommitment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='core.investor'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.coursemodule'),
        ),
        migrations.AddField(
            model_name='lessoncompletion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lesson'),
        ),
        migrations.AddField(
            model_name='lessoncompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.project'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.project'),
        ),
        migrations.AddField(
            model_name='projectscore',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.project'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webinarregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webinarregistration',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.webinar'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['project', 'category'], name='idx_pf_proj_cat'),
        ),
        migrations.AddIndex(
            model_name='projectscore',
            index=models.Index(fields=['project', 'pillar'], name='idx_ps_proj_pillar'),
        ),
    ]
