# Generated by Django 5.2.12 on 2026-03-16 02:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_investorcommitment_notes_investorcommitment_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvaluation',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_by', models.CharField(help_text='Email of the analyst who submitted the final evaluation.', max_length=255)),
                ('score_data', models.JSONField(blank=True, default=dict, help_text="Full DealScore.to_dict() output plus 'ai_meta' block.")),
                ('total_score', models.FloatField(default=0.0, help_text='Normalised total score (0-100) from ScoringEngine.')),
                ('verdict', models.CharField(blank=True, help_text='Verdict string: fast_track | watchlist | passed | blocked.', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.project')),
            ],
            options={
                'db_table': 'project_evaluations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='idx_pe_project'), models.Index(fields=['evaluated_by'], name='idx_pe_analyst')],
            },
        ),
    ]
