# Generated by Django 5.2.12 on 2026-04-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_user_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="featured_image_file",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image file directly (JPG/PNG/WebP, ≥1200×630 px recommended). If both a URL and a file are provided, the uploaded file takes priority.",
                null=True,
                upload_to="articles/",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="featured_image",
            field=models.CharField(
                blank=True,
                help_text="Paste a public image URL here, OR upload a file below.",
                max_length=500,
                null=True,
            ),
        ),
    ]
