# Generated by Django 5.2.12 on 2026-05-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_article_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(default='entrepreneur', help_text="Comma-separated roles. Valid roles: 'entrepreneur', 'investor' (LP), 'gp_investor' (GP Shareholder), 'admin', 'super_admin'.", max_length=255),
        ),
    ]
