# Generated by Django 5.2.12 on 2026-05-01 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pillar', models.CharField(choices=[('vision', 'Vision'), ('growth', 'Growth'), ('leadership', 'Leadership'), ('insight', 'Insight'), ('partnership', 'Partnership')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('total_articles', models.IntegerField(default=10)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Series',
                'db_table': 'article_series',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='teaser_text',
            field=models.TextField(blank=True, help_text='Short preview. If empty, auto-generated from content.', null=True),
        ),
        migrations.AlterField(
            model_name='rolerequest',
            name='requested_role',
            field=models.CharField(choices=[('entrepreneur', 'Entrepreneur'), ('investor', 'Investor'), ('reader', 'Reader'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(default='entrepreneur', help_text="Comma-separated roles. Valid roles: 'entrepreneur', 'investor' (LP), 'gp_investor' (GP Shareholder), 'reader', 'admin', 'super_admin'.", max_length=255),
        ),
        migrations.CreateModel(
            name='DownloadableTool',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='tools/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('excel', 'Excel Spreadsheet')], max_length=20)),
                ('requires_subscription', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='core.article')),
            ],
            options={
                'db_table': 'downloadable_tools',
            },
        ),
        migrations.CreateModel(
            name='ReaderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_articles', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reader_profiles',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.series'),
        ),
        migrations.CreateModel(
            name='ArticleCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article_completions',
                'unique_together': {('user', 'article')},
            },
        ),
    ]
